# Generated by Django 6.1 on 2026-08-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=32, unique=True)),
                ('event_date', models.DateField(null=True)),
                ('category_code', models.CharField(blank=True, max_length=16)),
                ('actor_id', models.CharField(blank=True, max_length=16, null=True)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('state', models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed'), ('VOIDED', 'Voided')], max_length=16)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_records', to='reconciliation.location')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=32, unique=True)),
                ('raw_record_ref', models.CharField(max_length=64)),
                ('normalized_record_ref', models.CharField(db_index=True, max_length=32)),
                ('raw_location_id', models.CharField(blank=True, max_length=32)),
                ('recorded_on', models.DateField(null=True)),
                ('raw_value', models.CharField(blank=True, max_length=32)),
                ('parsed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_entries', to='reconciliation.location')),
                ('matched_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_entries', to='reconciliation.systemarecord')),
            ],
        ),
        migrations.CreateModel(
            name='Disagreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MISSING_IN_B', 'In System A, no entry in System B'), ('ORPHAN_ENTRY', 'System B entry references a record that does not exist'), ('DUPLICATE_ENTRY', 'Same record entered into System B twice'), ('VALUE_MISMATCH', 'Systems report different values'), ('DATE_MISMATCH', 'Systems report different dates'), ('LOCATION_MISMATCH', 'Systems disagree on the location')], db_index=True, max_length=32)),
                ('a_value', models.CharField(blank=True, max_length=128)),
                ('b_value', models.CharField(blank=True, max_length=128)),
                ('sort_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disagreements', to='reconciliation.location')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disagreements', to='reconciliation.organization')),
                ('system_a_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disagreements', to='reconciliation.systemarecord')),
                ('system_b_entries', models.ManyToManyField(blank=True, related_name='disagreements', to='reconciliation.systembentry')),
            ],
            options={
                'ordering': ['-sort_value'],
            },
        ),
    ]
